# Step 5 — Installs & Popularity
print("Running Installs & Popularity Analysis...")

plt.figure(figsize=(10, 5))
sns.histplot(np.log10(df['Installs'] + 1), bins=30, kde=True, color='coral')
plt.title('Distribution of Installs (Log10 Scale)')
plt.xlabel('Log10(Installs)')
plt.ylabel('Count of Apps')
plt.savefig('output/5_1_installs_distribution.png')
plt.show()

top_50_apps = df[['App', 'Category', 'Installs']].sort_values(by='Installs', ascending=False).head(50)
print("Top 10 Most Installed Apps:")
display(top_50_apps.head(10))

avg_installs_cat = df.groupby('Category')['Installs'].mean().sort_values(ascending=False).head(20)
plt.figure(figsize=(12, 6))
sns.barplot(x=avg_installs_cat.index, y=avg_installs_cat.values, palette='crest')
plt.xticks(rotation=90)
plt.title('Average Installs per Category (Top 20)')
plt.ylabel('Average Installs')
plt.tight_layout()
plt.savefig('output/5_2_avg_installs_category.png')
plt.show()

free_vs_paid = df.groupby('Type')['Installs'].mean()
plt.figure(figsize=(6, 5))
sns.barplot(x=free_vs_paid.index, y=free_vs_paid.values, palette='Set2')
plt.title('Average Installs: Free vs Paid')
plt.ylabel('Average Installs')
plt.yscale('log')
plt.savefig('output/5_3_free_vs_paid_installs.png')
plt.show()
